name: data_profiling
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython=8.22.2
  - ipywidgets=8.1.3
  - jupyterlab=4.2.2
  - numpy=1.26.4
  - pandas=2.2.2
  - python=3.12.3
  - ydata-profiling=4.8.3
  - sqlalchemy=2.0.29 
